- name: Install Tomcat
  unarchive:
    src: "{{tomcat_url}}"
    dest: /usr/local/
    remote_src: yes

- name: Rename Dir
  shell: rm -rf tomcat* ; mv apache-tomcat-{{tomcat_release}} tomcat
  args:
    chdir: /usr/local/
    warn: false

- name: Grant execution permission
  shell: chmod +x *.sh
  args:
    chdir: /usr/local/tomcat/bin/
    warn: false

- name: Config java and tomcat env
  blockinfile:
    path: /usr/local/tomcat/bin/catalina.sh
    insertafter: "^# OS specific support"
    block: |
      CATALINA_HOME=/usr/local/tomcat
      JAVA_HOME=/usr/lib/jvm/java
  
- name: config tomcat service
  copy:
    src: tomcat.service
    dest: /usr/lib/systemd/system/tomcat.service
  when: ansible_os_family == 'RedHat'

- name: config tomcat service
  copy:
    src: tomcat.service
    dest: /lib/systemd/system/tomcat.service
  when: ansible_os_family == 'Debian'

- name: Set softlink on websoft9 workdir
  shell: ln -sf /usr/local/tomcat/webapps /data/wwwroot

- name: Start Tomcat
  service:
    name: tomcat
    enabled: yes
    state: started

# check version
- name: Check tomcat version
  shell: >
    sudo echo $(/usr/local/tomcat/bin/version.sh |grep -i "Server version") |sudo tee -a /data/logs/install_version.txt 
