- name: Install Tomcat
  unarchive:
    src: "{{tomcat_url}}"
    dest: /usr/local/
    remote_src: yes

- name: Rename Dir
  shell: rm -rf tomcat* ; mv apache-tomcat-{{tomcat_release}} tomcat
  args:
    chdir: /usr/local/
    warn: false

- name: Grant execution permission
  shell: chmod +x *.sh
  args:
    chdir: /usr/local/tomcat/bin/
    warn: false

- name: config tomcat service
  copy:
    src: tomcat.service
    dest: /usr/lib/systemd/system/tomcat.service
  when: ansible_os_family == 'RedHat'

- name: config tomcat service
  copy:
    src: tomcat.service
    dest: /lib/systemd/system/tomcat.service
  when: ansible_os_family == 'Debian'


- name: Config tomcat
  copy:
    src: server.xml
    dest: /usr/local/tomcat/conf/server.xml

- name: Create dir
  file:
    path: /data/wwwroot/
    state: directory

- name: Start Tomcat
  service:
    name: tomcat
    enabled: yes
    state: started
